#! /usr/bin/env ruby
# conding: utf-8

#
# git-gems -- rubygem utililty: bundler and git wrapper
#
# Usage:
#   git-gems bundler [OPTIONS]                   # do bundle install.
#   git-gems exec [COMMAND] [OPTIONS]            # do bundle exec .
#   git-gems help [COMMAND]                      # Describe available commands or one specific command
#   git-gems init                                # initilalize ruby project
#   git-gems release [--version] [version_name]  # taged release-tag
#   git-gems update                              # update bundled gems
#
#
# Copyright (c) 2015 Hiroshi IKEGAMI
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#


require 'rubygems'
require File.expand_path('../lib/git/gems', File.dirname(__FILE__))

Git::Gems::CLI.start(ARGV)

__END__
